changelog:
  categories:
    - title: New Features ✨
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: General Polish 🦾
      labels:
        - polish
    - title: Technical Improvement 🛠
      labels:
        - technical improvement
    - title: Documentation 📚
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
